######################################################################
#
# File name : tb_lvds_rx_data_wave.do
# Created on: Thu Feb 22 12:00:01 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
