######################################################################
#
# File name : tb_lvds_rx_data_compile.do
# Created on: Mon Mar 04 16:03:00 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../lvds_rx.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lvds_rx.srcs/sources_1/new/get_clk.v" \
"../../../../lvds_rx.srcs/sources_1/new/lvds_rx_data.v" \
"../../../../lvds_rx.srcs/sim_1/new/tb_lvds_rx_data.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

